apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vpc-authentication
  name: vpc-authentication
  namespace: vpc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc-authentication
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vpc-authentication
    spec:
      containers:
      - env:
        - name: SERVICENAME
          value: vpc-authentication
        - name: TZ
          value: Europe/Riga
        - name: ASPNETCORE_URLS
          value: http://+:5000
        image: ghcr.io/vismahorizon/horizon.authentication.service:650.4
        imagePullPolicy: Always
        name: authentication-service
        resources: {}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: appsettings
          mountPath: /app/appsettings.xml
          subPath: appsettings.xml
        - name: nlog
          mountPath: /app/nlog.config
          subPath: nlog.config
        - name: ftg20db
          mountPath: /app/FTG20DB.INI
          subPath: FTG20DB.INI        
      restartPolicy: Always
      volumes:
      - name: appsettings
        configMap:
          name: vpc-as-settings
          items:
            - key: appsettings.xml
              path: appsettings.xml
      - name: nlog
        configMap:
          name: vpc-as-settings
          items:
            - key: nlog.config
              path: nlog.config
      - name: ftg20db
        configMap:
          name: vpc-as-settings
          items:
            - key: FTG20DB.INI
              path: FTG20DB.INI             
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
status: {}