apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vpc-standardization
  name: vpc-standardization
  namespace: vpc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc-standardization
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vpc-standardization
    spec:
      containers:
      - env:
        - name: SERVICENAME
          value: vpc-standardization
        - name: TZ
          value: Europe/Riga
        image: ghcr.io/vismahorizon/horizon.vpc.standardization.service:460.6
        imagePullPolicy: Always
        name: standardization-service
        resources: {}
        volumeMounts:
        - name: appsettings
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        - name: app-log
          mountPath: /app/logs
      restartPolicy: Always
      volumes:
      - name: app-log
        emptyDir:
          medium: Memory
      - name: appsettings
        configMap:
          name: vpc-standardization-settings
          items:
            - key: appsettings.json
              path: appsettings.json
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
status: {}
